### ISSUE TITLE
esbuild-styled-components inject namespace

### ISSUE THREAD

**Issue by HEHOHADA** [lukalabs/lukalabs-npm#3]
Add the ability to set a namespace param to plugin  file `traverseAndPrint.js` already knows how to handle it

<img width="682" alt="image" src="https://user-images.githubusercontent.com/42976899/188875385-3cd9bf57-39a0-4326-b67d-d8a14a0650e2.png">

namespace should injected into opts

**Comment by alexkuz** [comment]
@HEHOHADA thank you! Should work in v1.0.1
