### ISSUE TITLE
Update to new tree-sitter to install on node 18 and higher

### ISSUE THREAD

**Issue by stijnvanderlaan** [lukalabs/lukalabs-npm#4]
Tree-sitter can't be installed on node 18 and higher, but this comment suggests it's fixed in version 0.20.1:
https://github.com/tree-sitter/node-tree-sitter/issues/106#issuecomment-1292854052

**Comment by alexkuz** [comment]
@stijnvanderlaan thank you! tree-sitter updated in v1.0.1
